dbfilepath: E:\coding\wow_tools_docker\extract\dbfilesclient\
hotfixfile: D:\Games\World of Warcraft\_retail_\Cache\ADB\deDE\DBCache.bin

ignored: [
			88587, # Iron Belly Spirits
			110586, # Mysterious Flower
			119220, # Alliance Gladiator's Banner
			119221, # Horde Gladiator's Banner
			129111, # Kvaldir Raiding Horn
			130249, # Waywatcher's Boon
			141300, # Magi Focusing Crystal
			143545, # Fel Focusing Crystal
			166851, # Kojo's Master Matching Set
]