local _, ADDON = ...

ADDON.L = {}
local L = ADDON.L

L["FAVOR_DISPLAYED"] = "All Displayed"
L["FAVOR_PER_CHARACTER"] = "Per Character"
L["Hidden"] = "Hidden"
L["RANDOM_TOY_DESCRIPTION"] = "The toy will be chosen randomly from the favorites."
L["RANDOM_TOY_TITLE"] = "Use Random Favorite Toy"
L["Reset filters"] = "Reset filters"
L["TASK_END"] = "[TBE] Phew! I'm done."
L["TASK_FAVOR_START"] = "[TBE] Reapplying stars all over your toys. Please wait a few seconds until I'm finished."
L["Toys"] = "Toys"
L["Usable"] = "Usable"
L["Day of the Dead"] = "Day of the Dead"
L["Pirates' Day"] = "Pirates' Day"

-- Settings
L["SETTING_CURSOR_KEYS"] = "Enable Left&Right keys to flip pages"
L["SETTING_FAVORITE_PER_CHAR"] = "Favorite toys per character"
L["SETTING_REPLACE_PROGRESSBAR"] = "Replace progress bar with achievement points"

-- Source
L["Black Market"] = "Black Market"
L["Enchanting"] = "Enchanting"
L["Engineering"] = "Engineering"
L["Jewelcrafting"] = "Jewelcrafting"
L["Leatherworking"] = "Leatherworking"
L["Order Hall"] = "Order Hall"
L["Pick Pocket"] = "Pick Pocket"
L["Treasure"] = "Treasure"

-- Effects
L["Effect"] = "Effect"
L["Appearance"] = "Appearance"
L["Consumable"] = "Consumable"
L["Controller"] = "Controller"
L["Interactable"] = "Interactable"
L["Transportation"] = "Transportation"
L["Perception"] = "Perception"
L["Minor"] = "Minor"
L["Bigger"] = "Bigger"
L["Smaller"] = "Smaller"
L["Pennant"] = "Pennant"
L["Alcohol"] = "Alcohol"
L["Aircraft"] = "Aircraft"
L["Tonk"] = "Tonk"
L["Vision"] = "Vision"
L["Nearby"] = "Nearby"
L["Act"] = "Act"
L["Statue"] = "Statue"
L["Banner"] = "Banner"
L["Clone"] = "Clone"
L["Firework"] = "Firework"
L["Ground"] = "Ground"
L["Chair"] = "Chair"
L["Clickable"] = "Clickable"
L["NPC"] = "NPC"
L["Target Dummy"] = "Target Dummy"
L["Co-op"] = "Co-op"
L["Skinning"] = "Skinning"
L["Taunt"] = "Taunt"
L["Transform"] = "Transform"
L["Voice"] = "Voice"
L["Fly/Fall"] = "Fly/Fall"
L["Flight Path"] = "Flight Path"
L["Hearthstone"] = "Hearthstone"
L["Run"] = "Run"
L["Swim"] = "Swim"
L["Teleport"] = "Teleport"
L["Water Walk"] = "Water Walk"
